# Generated by Django 2.1.7 on 2019-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20190311_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
