# Generated by Django 2.1.7 on 2019-03-15 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0009_auto_20190313_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
