# Generated by Django 2.1.7 on 2019-03-15 18:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0009_auto_20190313_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
