# Generated by Django 2.1.7 on 2019-03-15 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0011_auto_20190315_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.AddField(
            model_name='post',
            name='permissioned_users',
            field=models.ManyToManyField(blank=True, related_name='permissioned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
