# Generated by Django 2.1.7 on 2019-03-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0013_auto_20190315_1803'),
        ('paste', '0012_auto_20190315_1813'),
    ]

    operations = [
    ]
